name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.10"
            optional-deps: true
            pandas-version: "==1.5.3"
          - python-version: "3.11"
            optional-deps: false
            pandas-version: "==2.0.3"
          - python-version: "3.12"
            optional-deps: true
            pandas-version: "==2.1.0"
          - python-version: "3.13"
            optional-deps: false
            pandas-version: ">2.2.0"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        uv pip install pandas${{ matrix.pandas-version }}
        if [ "${{ matrix.optional-deps }}" = "true" ]; then
          uv pip install thefuzz[speedup]
        fi
        uv pip install -e .
    - name: Test with pytest
      run: |
        uv pip install pytest pytest-httpserver
        pytest
